mcwics2024/mcrap/urls.py
from django.urls import path
from .views import rap_transform, mcrap


app_name='mcrap'
urlpatterns = [
    path('', mcrap, name='mcrap'),
    path('rap_transform/', rap_transform, name='rap_transform'),
]

mcwics2024/mcwics2024/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcrap.urls'))
]

mcwics2024/mcrap/models.py
from django.db import models

# Create your models here.

mcwics2024/mcrap/forms.py
from django import forms

class TextForm(forms.Form):
    text = forms.CharField(label='Enter your notes', max_length=256)

mcwics2024/mcrap/views.py
from django.shortcuts import render
from django.conf import settings
from .forms import TextForm
import cohere
from gtts import gTTS
from pydub import AudioSegment
from pydub.playback import play
from django.utils.safestring import mark_safe
import json
import re


client = cohere.Client('xiRQw9XMonQhgxXa3x2WLAfuG7tdQwBAerIEPiUz')
def mcrap(request):
    return render(request, 'mcrap/main.html')

def rap_transform(request):
    # Initialize clean_lyrics_json with an empty list or default value
    clean_lyrics_json = mark_safe(json.dumps([]))

    if request.method == "POST":
        rap_song_input = request.POST.get('rap_song')
        if rap_song_input:
            rap_song = createRap(rap_song_input)
            rap_split = rap_song.split('\n')
            clean_lyrics = []
            for lyric in rap_split:
                if "(" not in lyric and "[" not in lyric and ":" not in lyric and lyric != "":
                    clean_lyrics.append(lyric)
            clean_lyrics = clean_lyrics[:-3]  # Assuming you want to remove the last element for some reason
            # Update clean_lyrics_json within the if block
            clean_lyrics_json = mark_safe(json.dumps(clean_lyrics))

    # Ensure clean_lyrics_json is passed in the context regardless of the POST condition
    return render(request, 'mcrap/output.html', {'rap_song': clean_lyrics_json, 'inital_song': clean_lyrics})


def createRap(text):
    response = client.generate(
        prompt=f'''Imagine youre the greatest rap lyricist of all time -- write a rap about these notes but make it help with 
        comprehension, please dont add any additional text except the lyrics of the song, also prioritze rhyming over everything: {text}''',
    )
    return response.generations[0].text

def increaseSpeed(song, target_speed=1.5):
    speech = AudioSegment.from_mp3("rap.mp3")
    new_speed = speech.speedup(playback_speed=target_speed)
    new_speed.export("modified_speech.mp3", format="mp3")

mcwics2024/mcrap/templates/mcrap/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300&display=swap" rel="stylesheet">
    <title>Home</title>
</head>
<body>
    <div class="form-container">
        <img src="{% static 'mcraplogo.png' %}" alt="Logo" width="531" height="132">
        <br>
        <br>
        <br>
        <form method="post" action="{% url 'mcrap:rap_transform' %}">
            {% csrf_token %}
            <textarea id="rap_song" name="rap_song" rows="20" cols="70" placeholder="Type your notes here..."></textarea>
            <br><br>
            <button class="button-57" role="button" onclick="showLoading(this)" type="submit">
                <div class="text">Generate Rap</div>
                <span>Generate Rap</span>
            </button>        
        </form>
    </div>
</body>
</html>

mcwics2024/mcrap/templates/mcrap/output.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>McRap</title> 
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <div style="background-color:black;">
        <img src="{% static 'mcraplogo.png' %}" alt="Logo" height="75">
    </div>
    <br>
    <div class = "container" style="background-color:#92221C;padding:20px;">
        <h1> Your Rap </h1>
        {% for verse in inital_song %}
            <div>{{ verse }}</div>
        {% endfor %}
    </div>
    <div class = "container" style="background-color:#92221C;padding:20px;">
        <h1> Sing Along </h1>
        <audio id="myAudio">
            <source src="{% static 'version3.mp3' %}" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
        <button onclick="playAudio(0)" class="button-57" role="button">
            <div class="text">Play</div>
            <span>Play</span>
        </button>
        <button onclick = "playAudio(1)" class="button-57" role="button">
            <div class="text">Stop</div>
            <span>Stop</span>
        </button>
        <br>
        <br>
        <div id="line"></div>
    </div>
    <br>

    <script>
        // Manually parse the JSON-encoded rap_song data from Django
        const rapList = {{ rap_song|safe }};

        function playAudio(cancel) {
            var audio = document.getElementById("myAudio");
            audio.loop = true;
            if (cancel==0){
                audio.play();
                displayLines();
            } if (cancel==1){
                document.getElementById("line").innerHTML = "";
                audio.pause();
                audio.currentTime = 0;
                clearInterval(incr);
                clearInterval(print);
            }
        }

        function displayLines(){

            var index = -1;
            incr = setInterval( () => {
                (index += 1);
            }, 3000)
            
            print = setInterval( () => {
                display(index)
            }, 3000);

            //rapList.forEach((line, index) => {
                //setTimeout(() => { display(line); }, 3000 * index);
            //});
        }

        function display(index){
            var msg = new SpeechSynthesisUtterance();
            msg.text = rapList[index];

            var wordsArray = rapList[index].split(" ");
            var syllables = 0
            for (let i = 0; i < wordsArray.length; i++) {
                var num = countSyllables(wordsArray[i]);
                if (wordsArray[i].includes(",") && (i < wordsArray.length - 1)){
                    syllables += 1
                }
                syllables +=  num;
            }
            if (syllables > 10 ) {
                msg.rate = 1 + (.1 * (syllables-10));
            }
            if (syllables < 5){
                msg.rate = 1 - (.05 * (syllables));
            }
            window.speechSynthesis.speak(msg);
            document.getElementById("line").innerHTML += rapList[index] + "<br>";
        }
        function countSyllables(word) {
            // Convert the word to lowercase and remove non-alphabetic characters
            word = word.toLowerCase().replace(/[^a-z]/g, '');

            // Remove common suffixes
            word = word.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/, '');

            // Count vowel sequences (but not diphthongs or single vowels at the end)
            const matches = word.match(/[aeiouy]{1,2}/g);
            
            return matches ? matches.length : 1;  // Assume at least one syllable if no matches found
        }
    </script>
</body>
</html>